#ifndef MYKERNEL_VERSION_H
#define MYKERNEL_VERSION_H
#define MYKERNEL_VERSION_MAJOR 1
#define MYKERNEL_VERSION_MINOR 5
#define MYKERNEL_VERSION_PATCH 1
#define MYKERNEL_VERSION_STRING "1.5.1"
#endif
